version: "3.8"
services: 
    server:
        image: jekyll/jekyll
        environment: 
            - JEKYLL_ENV=development
        volumes: 
            - .:/srv/jekyll
            - ./vendor/bundle:/usr/local/bundle:cached
        command: bash -c "bundle update && bundle exec jekyll serve --watch --incremental --host=0.0.0.0"
        ports:
            - 4000:4000